name: Release and Publish
on:
  push:
    branches:
      - main
jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating tags and releases
      id-token: write  # Needed for npm provenance
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Release
        uses: justincy/github-action-npm-release@2.0.2
        id: release
      - uses: actions/setup-node@v4
        if: steps.release.outputs.released == 'true'
        with:
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        if: steps.release.outputs.released == 'true'
        uses: pnpm/action-setup@v2
      - if: steps.release.outputs.released == 'true'
        run: pnpm i
      - name: Publish
        if: steps.release.outputs.released == 'true'
        run: pnpm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}