name: Auto Tag on Package Version Change
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Release
        uses: justincy/github-action-npm-release@2.0.2
        id: release